/*
 * Digitalization of Asset Counting Web Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AssetResource : IEquatable<AssetResource>
    { 
        /// <summary>
        /// Gets or Sets AssetNumber
        /// </summary>
        [DataMember(Name="assetNumber")]
        public string AssetNumber { get; set; }

        /// <summary>
        /// Gets or Sets SubNumber
        /// </summary>
        [DataMember(Name="subNumber")]
        public string SubNumber { get; set; }

        /// <summary>
        /// Gets or Sets CompanyCode
        /// </summary>
        [DataMember(Name="companyCode")]
        public string CompanyCode { get; set; }

        /// <summary>
        /// Gets or Sets TagId
        /// </summary>
        [DataMember(Name="tagId")]
        public string TagId { get; set; }

        /// <summary>
        /// Gets or Sets SecondTagId
        /// </summary>
        [DataMember(Name="secondTagId")]
        public string SecondTagId { get; set; }

        /// <summary>
        /// Gets or Sets IsUntaggable
        /// </summary>
        [DataMember(Name="isUntaggable")]
        public bool? IsUntaggable { get; set; }

        /// <summary>
        /// Gets or Sets LastModified
        /// </summary>
        [DataMember(Name="lastModified")]
        public DateTime? LastModified { get; set; }

        /// <summary>
        /// Gets or Sets Created
        /// </summary>
        [DataMember(Name="created")]
        public DateTime? Created { get; set; }

        /// <summary>
        /// Gets or Sets Creator
        /// </summary>
        [DataMember(Name="creator")]
        public string Creator { get; set; }

        /// <summary>
        /// Gets or Sets InventoryNumber
        /// </summary>
        [DataMember(Name="inventoryNumber")]
        public string InventoryNumber { get; set; }

        /// <summary>
        /// Gets or Sets SerialNumber
        /// </summary>
        [DataMember(Name="serialNumber")]
        public string SerialNumber { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name="location")]
        public string Location { get; set; }

        /// <summary>
        /// Gets or Sets Room
        /// </summary>
        [DataMember(Name="room")]
        public string Room { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets CostCenter
        /// </summary>
        [DataMember(Name="costCenter")]
        public string CostCenter { get; set; }

        /// <summary>
        /// Gets or Sets CapitalisationDate
        /// </summary>
        [DataMember(Name="capitalisationDate")]
        public DateTime? CapitalisationDate { get; set; }

        /// <summary>
        /// Gets or Sets LastInventoryDate
        /// </summary>
        [DataMember(Name="lastInventoryDate")]
        public DateTime? LastInventoryDate { get; set; }

        /// <summary>
        /// Gets or Sets AcquisitionValue
        /// </summary>
        [DataMember(Name="acquisitionValue")]
        public double? AcquisitionValue { get; set; }

        /// <summary>
        /// Gets or Sets AssetSuperNumber
        /// </summary>
        [DataMember(Name="assetSuperNumber")]
        public string AssetSuperNumber { get; set; }

        /// <summary>
        /// Gets or Sets Vendor
        /// </summary>
        [DataMember(Name="vendor")]
        public string Vendor { get; set; }

        /// <summary>
        /// Gets or Sets TypeName
        /// </summary>
        [DataMember(Name="typeName")]
        public string TypeName { get; set; }

        /// <summary>
        /// Gets or Sets Plant
        /// </summary>
        [DataMember(Name="plant")]
        public string Plant { get; set; }

        /// <summary>
        /// Gets or Sets AssetClass
        /// </summary>
        [DataMember(Name="assetClass")]
        public string AssetClass { get; set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [DataMember(Name="quantity")]
        public double? Quantity { get; set; }

        /// <summary>
        /// Gets or Sets Unit
        /// </summary>
        [DataMember(Name="unit")]
        public string Unit { get; set; }

        /// <summary>
        /// Gets or Sets DeactivatedOn
        /// </summary>
        [DataMember(Name="deactivatedOn")]
        public DateTime? DeactivatedOn { get; set; }

        /// <summary>
        /// Gets or Sets IsDeactivated
        /// </summary>
        [DataMember(Name="isDeactivated")]
        public bool? IsDeactivated { get; set; }

        /// <summary>
        /// Gets or Sets CompanyCodeCurrency
        /// </summary>
        [DataMember(Name="companyCodeCurrency")]
        public string CompanyCodeCurrency { get; set; }

        /// <summary>
        /// Gets or Sets Comment
        /// </summary>
        [DataMember(Name="comment")]
        public string Comment { get; set; }

        /// <summary>
        /// Gets or Sets ShareTags
        /// </summary>
        [DataMember(Name="shareTags")]
        public bool? ShareTags { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AssetResource {\n");
            sb.Append("  AssetNumber: ").Append(AssetNumber).Append("\n");
            sb.Append("  SubNumber: ").Append(SubNumber).Append("\n");
            sb.Append("  CompanyCode: ").Append(CompanyCode).Append("\n");
            sb.Append("  TagId: ").Append(TagId).Append("\n");
            sb.Append("  SecondTagId: ").Append(SecondTagId).Append("\n");
            sb.Append("  IsUntaggable: ").Append(IsUntaggable).Append("\n");
            sb.Append("  LastModified: ").Append(LastModified).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  Creator: ").Append(Creator).Append("\n");
            sb.Append("  InventoryNumber: ").Append(InventoryNumber).Append("\n");
            sb.Append("  SerialNumber: ").Append(SerialNumber).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Room: ").Append(Room).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  CostCenter: ").Append(CostCenter).Append("\n");
            sb.Append("  CapitalisationDate: ").Append(CapitalisationDate).Append("\n");
            sb.Append("  LastInventoryDate: ").Append(LastInventoryDate).Append("\n");
            sb.Append("  AcquisitionValue: ").Append(AcquisitionValue).Append("\n");
            sb.Append("  AssetSuperNumber: ").Append(AssetSuperNumber).Append("\n");
            sb.Append("  Vendor: ").Append(Vendor).Append("\n");
            sb.Append("  TypeName: ").Append(TypeName).Append("\n");
            sb.Append("  Plant: ").Append(Plant).Append("\n");
            sb.Append("  AssetClass: ").Append(AssetClass).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  Unit: ").Append(Unit).Append("\n");
            sb.Append("  DeactivatedOn: ").Append(DeactivatedOn).Append("\n");
            sb.Append("  IsDeactivated: ").Append(IsDeactivated).Append("\n");
            sb.Append("  CompanyCodeCurrency: ").Append(CompanyCodeCurrency).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("  ShareTags: ").Append(ShareTags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AssetResource)obj);
        }

        /// <summary>
        /// Returns true if AssetResource instances are equal
        /// </summary>
        /// <param name="other">Instance of AssetResource to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AssetResource other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    AssetNumber == other.AssetNumber ||
                    AssetNumber != null &&
                    AssetNumber.Equals(other.AssetNumber)
                ) && 
                (
                    SubNumber == other.SubNumber ||
                    SubNumber != null &&
                    SubNumber.Equals(other.SubNumber)
                ) && 
                (
                    CompanyCode == other.CompanyCode ||
                    CompanyCode != null &&
                    CompanyCode.Equals(other.CompanyCode)
                ) && 
                (
                    TagId == other.TagId ||
                    TagId != null &&
                    TagId.Equals(other.TagId)
                ) && 
                (
                    SecondTagId == other.SecondTagId ||
                    SecondTagId != null &&
                    SecondTagId.Equals(other.SecondTagId)
                ) && 
                (
                    IsUntaggable == other.IsUntaggable ||
                    IsUntaggable != null &&
                    IsUntaggable.Equals(other.IsUntaggable)
                ) && 
                (
                    LastModified == other.LastModified ||
                    LastModified != null &&
                    LastModified.Equals(other.LastModified)
                ) && 
                (
                    Created == other.Created ||
                    Created != null &&
                    Created.Equals(other.Created)
                ) && 
                (
                    Creator == other.Creator ||
                    Creator != null &&
                    Creator.Equals(other.Creator)
                ) && 
                (
                    InventoryNumber == other.InventoryNumber ||
                    InventoryNumber != null &&
                    InventoryNumber.Equals(other.InventoryNumber)
                ) && 
                (
                    SerialNumber == other.SerialNumber ||
                    SerialNumber != null &&
                    SerialNumber.Equals(other.SerialNumber)
                ) && 
                (
                    Location == other.Location ||
                    Location != null &&
                    Location.Equals(other.Location)
                ) && 
                (
                    Room == other.Room ||
                    Room != null &&
                    Room.Equals(other.Room)
                ) && 
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                ) && 
                (
                    CostCenter == other.CostCenter ||
                    CostCenter != null &&
                    CostCenter.Equals(other.CostCenter)
                ) && 
                (
                    CapitalisationDate == other.CapitalisationDate ||
                    CapitalisationDate != null &&
                    CapitalisationDate.Equals(other.CapitalisationDate)
                ) && 
                (
                    LastInventoryDate == other.LastInventoryDate ||
                    LastInventoryDate != null &&
                    LastInventoryDate.Equals(other.LastInventoryDate)
                ) && 
                (
                    AcquisitionValue == other.AcquisitionValue ||
                    AcquisitionValue != null &&
                    AcquisitionValue.Equals(other.AcquisitionValue)
                ) && 
                (
                    AssetSuperNumber == other.AssetSuperNumber ||
                    AssetSuperNumber != null &&
                    AssetSuperNumber.Equals(other.AssetSuperNumber)
                ) && 
                (
                    Vendor == other.Vendor ||
                    Vendor != null &&
                    Vendor.Equals(other.Vendor)
                ) && 
                (
                    TypeName == other.TypeName ||
                    TypeName != null &&
                    TypeName.Equals(other.TypeName)
                ) && 
                (
                    Plant == other.Plant ||
                    Plant != null &&
                    Plant.Equals(other.Plant)
                ) && 
                (
                    AssetClass == other.AssetClass ||
                    AssetClass != null &&
                    AssetClass.Equals(other.AssetClass)
                ) && 
                (
                    Quantity == other.Quantity ||
                    Quantity != null &&
                    Quantity.Equals(other.Quantity)
                ) && 
                (
                    Unit == other.Unit ||
                    Unit != null &&
                    Unit.Equals(other.Unit)
                ) && 
                (
                    DeactivatedOn == other.DeactivatedOn ||
                    DeactivatedOn != null &&
                    DeactivatedOn.Equals(other.DeactivatedOn)
                ) && 
                (
                    IsDeactivated == other.IsDeactivated ||
                    IsDeactivated != null &&
                    IsDeactivated.Equals(other.IsDeactivated)
                ) && 
                (
                    CompanyCodeCurrency == other.CompanyCodeCurrency ||
                    CompanyCodeCurrency != null &&
                    CompanyCodeCurrency.Equals(other.CompanyCodeCurrency)
                ) && 
                (
                    Comment == other.Comment ||
                    Comment != null &&
                    Comment.Equals(other.Comment)
                ) && 
                (
                    ShareTags == other.ShareTags ||
                    ShareTags != null &&
                    ShareTags.Equals(other.ShareTags)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (AssetNumber != null)
                    hashCode = hashCode * 59 + AssetNumber.GetHashCode();
                    if (SubNumber != null)
                    hashCode = hashCode * 59 + SubNumber.GetHashCode();
                    if (CompanyCode != null)
                    hashCode = hashCode * 59 + CompanyCode.GetHashCode();
                    if (TagId != null)
                    hashCode = hashCode * 59 + TagId.GetHashCode();
                    if (SecondTagId != null)
                    hashCode = hashCode * 59 + SecondTagId.GetHashCode();
                    if (IsUntaggable != null)
                    hashCode = hashCode * 59 + IsUntaggable.GetHashCode();
                    if (LastModified != null)
                    hashCode = hashCode * 59 + LastModified.GetHashCode();
                    if (Created != null)
                    hashCode = hashCode * 59 + Created.GetHashCode();
                    if (Creator != null)
                    hashCode = hashCode * 59 + Creator.GetHashCode();
                    if (InventoryNumber != null)
                    hashCode = hashCode * 59 + InventoryNumber.GetHashCode();
                    if (SerialNumber != null)
                    hashCode = hashCode * 59 + SerialNumber.GetHashCode();
                    if (Location != null)
                    hashCode = hashCode * 59 + Location.GetHashCode();
                    if (Room != null)
                    hashCode = hashCode * 59 + Room.GetHashCode();
                    if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                    if (CostCenter != null)
                    hashCode = hashCode * 59 + CostCenter.GetHashCode();
                    if (CapitalisationDate != null)
                    hashCode = hashCode * 59 + CapitalisationDate.GetHashCode();
                    if (LastInventoryDate != null)
                    hashCode = hashCode * 59 + LastInventoryDate.GetHashCode();
                    if (AcquisitionValue != null)
                    hashCode = hashCode * 59 + AcquisitionValue.GetHashCode();
                    if (AssetSuperNumber != null)
                    hashCode = hashCode * 59 + AssetSuperNumber.GetHashCode();
                    if (Vendor != null)
                    hashCode = hashCode * 59 + Vendor.GetHashCode();
                    if (TypeName != null)
                    hashCode = hashCode * 59 + TypeName.GetHashCode();
                    if (Plant != null)
                    hashCode = hashCode * 59 + Plant.GetHashCode();
                    if (AssetClass != null)
                    hashCode = hashCode * 59 + AssetClass.GetHashCode();
                    if (Quantity != null)
                    hashCode = hashCode * 59 + Quantity.GetHashCode();
                    if (Unit != null)
                    hashCode = hashCode * 59 + Unit.GetHashCode();
                    if (DeactivatedOn != null)
                    hashCode = hashCode * 59 + DeactivatedOn.GetHashCode();
                    if (IsDeactivated != null)
                    hashCode = hashCode * 59 + IsDeactivated.GetHashCode();
                    if (CompanyCodeCurrency != null)
                    hashCode = hashCode * 59 + CompanyCodeCurrency.GetHashCode();
                    if (Comment != null)
                    hashCode = hashCode * 59 + Comment.GetHashCode();
                    if (ShareTags != null)
                    hashCode = hashCode * 59 + ShareTags.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(AssetResource left, AssetResource right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AssetResource left, AssetResource right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
