/*
 * Digitalization of Asset Counting Web Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InventoryOrderAsset : IEquatable<InventoryOrderAsset>
    { 
        /// <summary>
        /// Gets or Sets InventoryOrderId
        /// </summary>
        [Required]
        [DataMember(Name="inventoryOrderId")]
        public int? InventoryOrderId { get; set; }

        /// <summary>
        /// Gets or Sets Checked
        /// </summary>
        [DataMember(Name="checked")]
        public bool? Checked { get; set; }

        /// <summary>
        /// Gets or Sets LastModified
        /// </summary>
        [DataMember(Name="lastModified")]
        public DateTime? LastModified { get; set; }

        /// <summary>
        /// Gets or Sets Created
        /// </summary>
        [DataMember(Name="created")]
        public DateTime? Created { get; set; }

        /// <summary>
        /// Gets or Sets ChangedBy
        /// </summary>
        [DataMember(Name="changedBy")]
        public string ChangedBy { get; set; }

        /// <summary>
        /// Gets or Sets CommentOther
        /// </summary>
        [DataMember(Name="commentOther")]
        public string CommentOther { get; set; }

        /// <summary>
        /// Gets or Sets CommentCostCenter
        /// </summary>
        [DataMember(Name="commentCostCenter")]
        public string CommentCostCenter { get; set; }

        /// <summary>
        /// Gets or Sets CommentPlant
        /// </summary>
        [DataMember(Name="commentPlant")]
        public string CommentPlant { get; set; }

        /// <summary>
        /// Gets or Sets CommentLocation
        /// </summary>
        [DataMember(Name="commentLocation")]
        public string CommentLocation { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        
        public enum StatusEnum
        {
            
            /// <summary>
            /// Enum _0Enum for 0
            /// </summary>
            
            _0Enum = 0,
            
            /// <summary>
            /// Enum _1Enum for 1
            /// </summary>
            
            _1Enum = 1,
            
            /// <summary>
            /// Enum _2Enum for 2
            /// </summary>
            
            _2Enum = 2,
            
            /// <summary>
            /// Enum _3Enum for 3
            /// </summary>
            
            _3Enum = 3,
            
            /// <summary>
            /// Enum _4Enum for 4
            /// </summary>
            
            _4Enum = 4,
            
            /// <summary>
            /// Enum _5Enum for 5
            /// </summary>
            
            _5Enum = 5
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status")]
        public StatusEnum? Status { get; set; }

        /// <summary>
        /// Gets or Sets Asset
        /// </summary>
        [DataMember(Name="asset")]
        public Asset Asset { get; set; }

        /// <summary>
        /// Gets or Sets AssetNumber
        /// </summary>
        [Required]
        [DataMember(Name="assetNumber")]
        public string AssetNumber { get; set; }

        /// <summary>
        /// Gets or Sets SubNumber
        /// </summary>
        [Required]
        [DataMember(Name="subNumber")]
        public string SubNumber { get; set; }

        /// <summary>
        /// Gets or Sets CompanyCode
        /// </summary>
        [Required]
        [DataMember(Name="companyCode")]
        public string CompanyCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InventoryOrderAsset {\n");
            sb.Append("  InventoryOrderId: ").Append(InventoryOrderId).Append("\n");
            sb.Append("  Checked: ").Append(Checked).Append("\n");
            sb.Append("  LastModified: ").Append(LastModified).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  ChangedBy: ").Append(ChangedBy).Append("\n");
            sb.Append("  CommentOther: ").Append(CommentOther).Append("\n");
            sb.Append("  CommentCostCenter: ").Append(CommentCostCenter).Append("\n");
            sb.Append("  CommentPlant: ").Append(CommentPlant).Append("\n");
            sb.Append("  CommentLocation: ").Append(CommentLocation).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Asset: ").Append(Asset).Append("\n");
            sb.Append("  AssetNumber: ").Append(AssetNumber).Append("\n");
            sb.Append("  SubNumber: ").Append(SubNumber).Append("\n");
            sb.Append("  CompanyCode: ").Append(CompanyCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InventoryOrderAsset)obj);
        }

        /// <summary>
        /// Returns true if InventoryOrderAsset instances are equal
        /// </summary>
        /// <param name="other">Instance of InventoryOrderAsset to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InventoryOrderAsset other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    InventoryOrderId == other.InventoryOrderId ||
                    InventoryOrderId != null &&
                    InventoryOrderId.Equals(other.InventoryOrderId)
                ) && 
                (
                    Checked == other.Checked ||
                    Checked != null &&
                    Checked.Equals(other.Checked)
                ) && 
                (
                    LastModified == other.LastModified ||
                    LastModified != null &&
                    LastModified.Equals(other.LastModified)
                ) && 
                (
                    Created == other.Created ||
                    Created != null &&
                    Created.Equals(other.Created)
                ) && 
                (
                    ChangedBy == other.ChangedBy ||
                    ChangedBy != null &&
                    ChangedBy.Equals(other.ChangedBy)
                ) && 
                (
                    CommentOther == other.CommentOther ||
                    CommentOther != null &&
                    CommentOther.Equals(other.CommentOther)
                ) && 
                (
                    CommentCostCenter == other.CommentCostCenter ||
                    CommentCostCenter != null &&
                    CommentCostCenter.Equals(other.CommentCostCenter)
                ) && 
                (
                    CommentPlant == other.CommentPlant ||
                    CommentPlant != null &&
                    CommentPlant.Equals(other.CommentPlant)
                ) && 
                (
                    CommentLocation == other.CommentLocation ||
                    CommentLocation != null &&
                    CommentLocation.Equals(other.CommentLocation)
                ) && 
                (
                    Status == other.Status ||
                    Status != null &&
                    Status.Equals(other.Status)
                ) && 
                (
                    Asset == other.Asset ||
                    Asset != null &&
                    Asset.Equals(other.Asset)
                ) && 
                (
                    AssetNumber == other.AssetNumber ||
                    AssetNumber != null &&
                    AssetNumber.Equals(other.AssetNumber)
                ) && 
                (
                    SubNumber == other.SubNumber ||
                    SubNumber != null &&
                    SubNumber.Equals(other.SubNumber)
                ) && 
                (
                    CompanyCode == other.CompanyCode ||
                    CompanyCode != null &&
                    CompanyCode.Equals(other.CompanyCode)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (InventoryOrderId != null)
                    hashCode = hashCode * 59 + InventoryOrderId.GetHashCode();
                    if (Checked != null)
                    hashCode = hashCode * 59 + Checked.GetHashCode();
                    if (LastModified != null)
                    hashCode = hashCode * 59 + LastModified.GetHashCode();
                    if (Created != null)
                    hashCode = hashCode * 59 + Created.GetHashCode();
                    if (ChangedBy != null)
                    hashCode = hashCode * 59 + ChangedBy.GetHashCode();
                    if (CommentOther != null)
                    hashCode = hashCode * 59 + CommentOther.GetHashCode();
                    if (CommentCostCenter != null)
                    hashCode = hashCode * 59 + CommentCostCenter.GetHashCode();
                    if (CommentPlant != null)
                    hashCode = hashCode * 59 + CommentPlant.GetHashCode();
                    if (CommentLocation != null)
                    hashCode = hashCode * 59 + CommentLocation.GetHashCode();
                    if (Status != null)
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    if (Asset != null)
                    hashCode = hashCode * 59 + Asset.GetHashCode();
                    if (AssetNumber != null)
                    hashCode = hashCode * 59 + AssetNumber.GetHashCode();
                    if (SubNumber != null)
                    hashCode = hashCode * 59 + SubNumber.GetHashCode();
                    if (CompanyCode != null)
                    hashCode = hashCode * 59 + CompanyCode.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InventoryOrderAsset left, InventoryOrderAsset right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InventoryOrderAsset left, InventoryOrderAsset right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
