/*
 * Digitalization of Asset Counting Web Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class InventoryAssetStatisticsApiController : ControllerBase
    { 
        /// <summary>
        /// Returns asset statistic for specified inventory id.
        /// </summary>
        
        /// <param name="inventoryId">inventory id to get the statistic for.</param>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/api/inventoryassets/statistic")]
        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("Get")]
        [SwaggerResponse(statusCode: 200, type: typeof(InventoryOrderStatistic), description: "Success")]
        public virtual IActionResult Get([FromQuery]int? inventoryId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(InventoryOrderStatistic));

            string exampleJson = null;
            exampleJson = "{\n  \"broken\" : 5,\n  \"total\" : 6,\n  \"default\" : 1,\n  \"transferred\" : 3,\n  \"missed\" : 5,\n  \"active\" : 2,\n  \"id\" : 0,\n  \"remaining\" : 7,\n  \"research\" : 9\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<InventoryOrderStatistic>(exampleJson)
            : default(InventoryOrderStatistic);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Returns asset statistic for specified inventory id when searching or filtering data
        /// </summary>
        
        /// <param name="inventoryAssetFullTextAndPropertySearch">Query parameters for searching and paging</param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/inventoryassets/statistic")]
        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("Post")]
        [SwaggerResponse(statusCode: 200, type: typeof(InventoryOrderStatistic), description: "Success")]
        public virtual IActionResult Post([FromBody]InventoryAssetFullTextAndPropertySearch inventoryAssetFullTextAndPropertySearch)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(InventoryOrderStatistic));

            string exampleJson = null;
            exampleJson = "{\n  \"broken\" : 5,\n  \"total\" : 6,\n  \"default\" : 1,\n  \"transferred\" : 3,\n  \"missed\" : 5,\n  \"active\" : 2,\n  \"id\" : 0,\n  \"remaining\" : 7,\n  \"research\" : 9\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<InventoryOrderStatistic>(exampleJson)
            : default(InventoryOrderStatistic);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
