/*
 * Digitalization of Asset Counting Web Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class InventoriesValidationApiController : ControllerBase
    { 
        /// <summary>
        /// Returns if specified inventories are valid for email sending or completion
        /// </summary>
        
        /// <param name="inventoryOrderIds">The inventoryOrder list to be validated.</param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/inventories/validation")]
        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("Post")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<InventoryValidation>), description: "Success")]
        public virtual IActionResult Post([FromBody]List<int?> inventoryOrderIds)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<InventoryValidation>));

            string exampleJson = null;
            exampleJson = "[ {\n  \"valid\" : true,\n  \"id\" : 0,\n  \"remaining\" : 6\n}, {\n  \"valid\" : true,\n  \"id\" : 0,\n  \"remaining\" : 6\n} ]";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<InventoryValidation>>(exampleJson)
            : default(List<InventoryValidation>);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
