/*
 * Digitalization of Asset Counting Web Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class InventoriesActionsSendEmailApiController : ControllerBase
    { 
        /// <summary>
        /// Completes the inventoryOrder if not already completed and sends an email to the supervisor of the inventory order.
        /// </summary>
        
        /// <param name="id">The id of the inventory order object to send an email for.</param>
        /// <response code="204">Success</response>
        [HttpPost]
        [Route("/api/inventories/actions/sendemail")]
        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("Post")]
        public virtual IActionResult Post([FromQuery]int? id)
        { 
            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);


            throw new NotImplementedException();
        }

        /// <summary>
        /// Completes the inventoryOrders if not already completed and sends an email to the supervisors of the inventory orders.
        /// </summary>
        
        /// <param name="ids">The ids of the inventory orders to send an email for.</param>
        /// <response code="204">Success</response>
        [HttpPost]
        [Route("/api/inventories/actions/sendemail/bulk")]
        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("Post_0")]
        public virtual IActionResult Post_0([FromQuery]List<int?> ids)
        { 
            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);


            throw new NotImplementedException();
        }
    }
}
